[project]
name = "markdown-editor-api"
version = "0.1.0"
description = "FastAPI backend for markdown editor"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi==0.115.0",
  "uvicorn[standard]==0.32.0",
  "sqlalchemy==2.0.36",
  "python-jose[cryptography]==3.3.0",
  "passlib[bcrypt]==1.7.4",
  "bcrypt==4.0.1",
  "python-multipart==0.0.12",
  "pydantic[email]==2.10.0",
  "python-dotenv==1.0.1"
]
